FROM library/archlinux:latest AS build
ARG REPO_URL=https://ovosarchlinuxpackages.blob.core.windows.net/ovos-arch
ARG PACKAGE_CACHE_URI

VOLUME /target

WORKDIR /archlinux
RUN mkdir -p /archlinux/rootfs

RUN printf "\n\n[ovos-arch]\nSigLevel = Optional TrustAll\nServer = ${REPO_URL}/\$arch" >> /etc/pacman.conf \
    && if [ -n "${PACKAGE_CACHE_URI}" ]; then printf "#Modified\n\nServer = ${PACKAGE_CACHE_URI}\n" > /etc/pacman.d/mirrorlist ; fi
    
RUN pacman-key --init &&  pacman -Sy --noconfirm arch-install-scripts 
# qemu-img guestfs-tools

CMD ["/usr/bin/bash"]