name: "Arch package action(s)"
description: "GitHub Action to run Arch Linux's package tools"
author: 'valorekhov'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  operation:
    description: 'The operation to perform'
    required: true
    default: 'makefile-update'
  workingdir:
    description: 'The working directory to run the operation in'
    required: false
    default: ''
  packages:
    description: 'List of repo-relative paths to PKGBUILDs to operate on. Encoded as a JSON array.'
    required: false
    default: '[]'
  rebuildall:
    description: 'Rebuild all .SRCINFOs and/or packages without regard to modification status'
    required: false
    default: ''
  repourl:
    description: 'The URL of the repository online to use as a source of prebuilt packages'
    required: false
    default: ''
  

runs:
  using: 'docker'
  image: 'Dockerfile'