ARG ARCH=amd64
FROM archlinux-$ARCH:base-devel AS build

VOLUME /build

# RUN env | grep DBUS
RUN pacman-key --init && (pacman-key --populate archlinuxarm || true) \
    && pacman -Suy --noconfirm base-devel git python3 python-setuptools  \
    && rm -rf rootfs/var/lib/pacman/sync/* \
    && useradd -m build && echo "build ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/build \
    && mkdir -p /build && chown build:build /build \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen \
    && printf "\nPKGEXT='.pkg.tar.zst'\nMAKEFLAGS=\"-j$(nproc)\"" >> /etc/makepkg.conf \
    && printf "\n[ovos-arch]\nSigLevel = Optional TrustAll\nServer = file:///build/.repo/\$arch" >> /etc/pacman.confd

USER build
WORKDIR /build
RUN mkdir /home/build/.gnupg && \
    touch /home/build/.gnupg/gpg.conf && \
    echo "keyserver-options auto-key-retrieve" > /home/build/.gnupg/gpg.conf
